apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadpqys1967-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadpqys1967-tenant-component
    app.kubernetes.io/part-of: loadpqys1967-tenant-app
  name: loadpqys1967-tenant-component
  namespace: loadpqys1967-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadpqys1967-tenant-component
    weight: null
status: {}
